version: '3.12'
services:
  curiosity_math:
    build: .
    volumes:
      - .:/app
      - ./many_times_results:/app/many_times_results
    environment:
      - CUDA_VISIBLE_DEVICES=0  # 可以根据需要修改GPU ID
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python path/to/your/script.py